name: Build Enhanced DLL for Alkad 2588 WH
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      run: |
        echo Installing Visual Studio 2022 Build Tools...
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.Windows10SDK --add Microsoft.VisualStudio.Component.VC.CoreIde" -y || if errorlevel 3010 echo Reboot required but continuing...
        echo Waiting for Visual Studio Installer to complete...
        :wait_loop
        tasklist | findstr /i "vs_installershell" >nul
        if errorlevel 1 (goto :done_wait) else (timeout /t 10 >nul & goto :wait_loop)
        :done_wait
        echo Visual Studio Build Tools installed successfully.
      shell: cmd

    - name: Refresh Environment
      run: |
        refreshenv
        echo Refreshed environment variables.
      shell: cmd

    - name: Find Visual Studio Path with vswhere
      run: |
        for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do set "VS_PATH=%%i"
        if not defined VS_PATH (
          echo Visual Studio with required components not found.
          dir "C:\Program Files (x86)\Microsoft Visual Studio\2022" /s /p
          dir "C:\Program Files\Microsoft Visual Studio\2022" /s /p
          exit 1
        )
        echo Visual Studio found at: %VS_PATH%
        set "VCVARSALL_PATH=%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat"
        echo Using vcvarsall.bat at: %VCVARSALL_PATH%
        if not exist "%VCVARSALL_PATH%" (
          echo vcvarsall.bat not found at %VCVARSALL_PATH%
          exit
