name: Build Enhanced DLL for Alkad 2588 WH
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Visual Studio Paths
      run: |
        dir "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" 2>nul
        if errorlevel 1 dir "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" 2>nul
        if errorlevel 1 dir "C:\Program Files (x86)\Microsoft Visual Studio\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" 2>nul
        if errorlevel 1 dir "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" 2>nul
      shell: cmd

    - name: Setup MSBuild as Fallback
      uses: microsoft/setup-msbuild@v1
      if: failure()

    - name: Add ImGui Source
      run: |
        mkdir imgui
        curl -L -o imgui/imgui.zip https://github.com/ocornut/imgui/archive/refs/tags/v1.91.6.zip
        7z x imgui/imgui.zip -oimgui -y
        move imgui\imgui-1.91.6\* imgui\
        rmdir imgui\
