name: Build DLL for Alkad 2588 WH
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      run: |
        echo Installing Visual Studio 2022 Build Tools with nmake...
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.VC.Tools.All" -y || if errorlevel 3010 exit /b 0
        timeout /t 30 /nobreak >nul
        echo Checking vswhere...
        if not exist "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" (
          echo vswhere.exe not found. Installation failed.
          exit /b 1
        )
      shell: cmd

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
      with:
        msbuild-architecture: x64

    - name: Configure MSVC Environment
      run: |
        echo Configuring MSVC environment...
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
        if errorlevel 1 (
          echo Failed to run vcvarsall.bat.
          exit /b 1
        )
        where nmake
        if errorlevel 1 (
          echo nmake not found in PATH.
          echo Current PATH: %PATH%
          exit /b 1
        )
        echo nmake found successfully.
      shell: cmd

    - name: Add ImGui
      run: |
        echo Adding ImGui...
        mkdir imgui
        curl -L -o imgui/imgui.zip https://github.com/ocornut/imgui/archive/refs/tags/v1.91.6.zip || exit /b 1
        7z x imgui/imgui.zip -oimgui -y || exit /b 1
        move imgui\imgui-1.91.6\* imgui\
        rmdir /s /q imgui\imgui-1.91.6
        del imgui\imgui.zip
      shell: cmd

    - name: Add and Build Detours
      run: |
        echo Adding and building Detours...
        mkdir detours
        curl -L -o detours/detours.zip https://github.com/microsoft/Detours/archive/refs/tags/v4.0.1.zip || exit /b 1
        7z x detours/detours.zip -odetours -y || exit /b 1
        del detours\detours.zip
        cd detours\Detours-4.0.1
        nmake /f Makefile || exit /b 1
        if exist lib.X64\detours.lib xcopy lib.X64\detours.lib ..\ >nul
        if exist include\detours.h xcopy include\detours.h ..\ >nul
        cd ..\..
        rmdir /s /q detours\Detours-4.0.1
      shell: cmd

    - name: Build DLL
      run: |
        echo Building DLL...
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
        if errorlevel 1 (
          echo Failed to run vcvarsall.bat.
          exit /b 1
        )
        where cl
        if errorlevel 1 (
          echo cl.exe not found in PATH.
          echo Current PATH: %PATH%
          exit /b 1
        )
        cl /Y- /O2 /MD /W4 /TP /EHsc /D "WIN32_LEAN_AND_MEAN" /D "NOMINMAX" /D "_HAS_PCH=0" /I "imgui" /I "detours" /I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um" enhanced_hack_v2.cpp imgui\imgui.cpp imgui\imgui_draw.cpp imgui\imgui_widgets.cpp imgui\imgui_tables.cpp imgui\backends\imgui_impl_dx11.cpp imgui\backends\imgui_impl_win32.cpp /link /DLL /OUT:Dll1.dll /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" /LIBPATH:"detours" d3d11.lib d3dcompiler.lib detours.lib
        if errorlevel 1 (
          echo Failed to compile DLL.
          exit /b 1
        )
        if not exist Dll1.dll (
          echo Dll1.dll not found after compilation.
          dir /s /p
          exit /b 1
        )
        echo Dll1.dll created successfully.
      shell: cmd

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: Dll1.dll
        path: Dll1.dll
