name: Build Enhanced DLL for Alkad 2588 WH
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Find Visual Studio Path with vswhere
      run: |
        for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do set "VS_PATH=%%i"
        if not defined VS_PATH (
          echo Visual Studio with required components not found.
          exit 1
        )
        echo Visual Studio found at: %VS_PATH%
        set "VCVARSALL_PATH=%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat"
        echo Using vcvarsall.bat at: %VCVARSALL_PATH%
        if not exist "%VCVARSALL_PATH%" (
          echo vcvarsall.bat not found at %VCVARSALL_PATH%
          exit 1
        )
      shell: cmd
      continue-on-error: true

    - name: Configure MSVC Environment
      if: steps.FindVisualStudioPathWithVswhere.outcome == 'success'
      run: |
        call "%VCVARSALL_PATH%" x64
      shell: cmd

    - name: Fallback Setup for MSVC
      if: steps.FindVisualStudioPathWithVswhere.outcome != 'success'
      run: |
        echo Attempting to install Visual Studio Build Tools...
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64" -y
        for /f "tokens=*" %%i in ('"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath') do set "VS_PATH=%%i"
        if not defined VS_PATH (
          echo Visual Studio with required components still not found after installation.
          exit 1
        )
        echo Visual Studio found at: %VS_PATH%
        set "VCVARSALL_PATH=%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat"
        echo Using vcvarsall.bat at: %VCVARSALL_PATH%
        call "%VCVARSALL_PATH%" x64
      shell: cmd

    - name: Add ImGui Source
      run: |
        mkdir imgui
        curl -L -o imgui/imgui.zip https://github.com/ocornut/imgui/archive/refs/tags/v1.91.6.zip
        7z x imgui/imgui.zip -oimgui -y
        move imgui\imgui-1.91.6\* imgui\
        rmdir imgui\imgui-1.91.6
        del imgui\imgui.zip
      shell: cmd

    - name: Add Detours
      run: |
        mkdir detours
        curl -L -o detours/detours.zip https://github.com/microsoft/Detours/archive/refs/tags/v4.0.1.zip
        7z x detours/detours.zip -odetours -y
        del detours\detours.zip
        xcopy detours\Detours-4.0.1\* detours\ /E /S /Y /I
        if exist detours\Detours-4.0.1 rmdir /s /q detours\Detours-4.0.1
        if exist detours\lib.X64\detours.lib copy detours\lib.X64\detours.lib detours\
        if exist detours\include\detours.h copy detours\include\detours.h detours\
      shell: cmd

    - name: Build DLL
      run: |
        cl /Y- /O2 /MD /W4 /TP /EHsc /D "WIN32_LEAN_AND_MEAN" /D "NOMINMAX" /D "_HAS_PCH=0" /I "C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" /I "C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" /I "imgui" /I "detours" enhanced_hack_v2.cpp imgui\imgui.cpp imgui\imgui_draw.cpp imgui\imgui_widgets.cpp imgui\imgui_tables.cpp imgui\backends\imgui_impl_dx11.cpp imgui\backends\imgui_impl_win32.cpp /link /DLL /OUT:Dll1.dll /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64" /LIBPATH:"detours" d3d11.lib d3dcompiler.lib advapi32.lib winmm.lib detours.lib user32.lib
        if not exist Dll1.dll exit 1
      shell: cmd

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: Dll1.dll
        path: Dll1.dll
